import discord
from discord.ext import commands
from discord.ext.commands import Bot
import asyncio
import chalk
import requests
import io


bot = commands.Bot (command_prefix ='d!')
bot.remove_command('help')
bot.load_extension('cog')



@bot.event 
async def on_ready(pass_context=True):#000
    print ("Dexcord online!")
    print ("To pronto:" + bot.user.name)
    print ("ID:" + bot.user.id)

@bot.command(pass_context=True)
async def bulbasaur(ctx): #001
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x01DF3A) 
    embed.add_field(name="Nome: Bulbasaur", value="Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger.", inline=True)
    embed.add_field(name="Nº :", value="001", inline=True)
    embed.add_field(name="Altura:", value="0,7m", inline=True)
    embed.add_field(name="Categoria:",  value="Seed", inline=True)
    embed.add_field(name="Tipo:",   value="Grass/Poison", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Ice/Physhic", inline=True)
    embed.add_field(name="Evoluções:",  value="Bulbasaur ----> Ivysaur ----> Venusaur", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png')
    await bot.say (embed=embed)
   
@bot.command(pass_context=True)
async def Bulbasaur(ctx): #001
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x01DF3A) 
    embed.add_field(name="Nome: Bulbasaur", value="Bulbasaur can be seen napping in bright sunlight. There is a seed on its back. By soaking up the sun's rays, the seed grows progressively larger.", inline=True)
    embed.add_field(name="Nº :", value="001", inline=True)
    embed.add_field(name="Altura:", value="0,7m", inline=True)
    embed.add_field(name="Categoria:",  value="Seed", inline=True)
    embed.add_field(name="Tipo:",   value="Grass/Poison", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Ice/Physhic", inline=True)
    embed.add_field(name="Evoluções:",  value="Bulbasaur ----> Ivysaur ----> Venusaur", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Ivysaur(ctx): #002
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x01DF3A) 
    embed.add_field(name="Nome: Ivysaur", value="There is a bud on this Pokémon's back. To support its weight, Ivysaur's legs and trunk grow thick and strong. If it starts spending more time lying in the sunlight, it's a sign that the bud will bloom into a large flower soon.", inline=True)
    embed.add_field(name="Nº :", value="002", inline=True)
    embed.add_field(name="Altura:", value="1,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Seed", inline=True)
    embed.add_field(name="Tipo:",   value="Grass/Poison", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Ice/Physhic", inline=True)
    embed.add_field(name="Evoluções:",  value="Bulbasaur ----> Ivysaur ----> Venusaur", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def ivysaur(ctx): #002
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x01DF3A) 
    embed.add_field(name="Nome: Ivysaur", value="There is a bud on this Pokémon's back. To support its weight, Ivysaur's legs and trunk grow thick and strong. If it starts spending more time lying in the sunlight, it's a sign that the bud will bloom into a large flower soon.", inline=True)
    embed.add_field(name="Nº :", value="002", inline=True)
    embed.add_field(name="Altura:", value="1,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Seed", inline=True)
    embed.add_field(name="Tipo:",   value="Grass/Poison", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Ice/Physhic", inline=True)
    embed.add_field(name="Evoluções:",  value="Bulbasaur ----> Ivysaur ----> Venusaur", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/002.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Venusaur(ctx): #003
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x01DF3A) 
    embed.add_field(name="Nome: Venusaur", value="There is a large flower on Venusaur's back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower's aroma soothes the emotions of people.", inline=True)
    embed.add_field(name="Nº :", value="003", inline=True)
    embed.add_field(name="Altura:", value="2,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Seed", inline=True)
    embed.add_field(name="Tipo:",   value="Grass/Poison", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Ice/Physhic", inline=True)
    embed.add_field(name="Evoluções:",  value="Bulbasaur ----> Ivysaur ----> Venusaur", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def venusaur(ctx): #003
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x01DF3A) 
    embed.add_field(name="Nome: Venusaur", value="There is a large flower on Venusaur's back. The flower is said to take on vivid colors if it gets plenty of nutrition and sunlight. The flower's aroma soothes the emotions of people.", inline=True)
    embed.add_field(name="Nº :", value="003", inline=True)
    embed.add_field(name="Altura:", value="2,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Seed", inline=True)
    embed.add_field(name="Tipo:",   value="Grass/Poison", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Ice/Physhic", inline=True)
    embed.add_field(name="Evoluções:",  value="Bulbasaur ----> Ivysaur ----> Venusaur", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/003.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Charmander(ctx): #004
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Charmander", value="The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely.", inline=True)
    embed.add_field(name="Nº :", value="004", inline=True)
    embed.add_field(name="Altura:", value="0,6 m", inline=True)
    embed.add_field(name="Categoria:",  value="Lizard", inline=True)
    embed.add_field(name="Tipo:",   value="Fire", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ground/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def charmander(ctx): #004
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Charmander", value="The flame that burns at the tip of its tail is an indication of its emotions. The flame wavers when Charmander is enjoying itself. If the Pokémon becomes enraged, the flame burns fiercely.", inline=True)
    embed.add_field(name="Nº :", value="004", inline=True)
    embed.add_field(name="Altura:", value="0,6 m", inline=True)
    embed.add_field(name="Categoria:",  value="Lizard", inline=True)
    embed.add_field(name="Tipo:",   value="Fire", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ground/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Charmeleon(ctx): #005
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Charmeleon", value="Charmeleon mercilessly destroys its foes using its sharp claws. If it encounters a strong foe, it turns aggressive. In this excited state, the flame at the tip of its tail flares with a bluish white color.", inline=True)
    embed.add_field(name="Nº :", value="005", inline=True)
    embed.add_field(name="Altura:", value="1,1 m", inline=True)
    embed.add_field(name="Categoria:",  value="Flame", inline=True)
    embed.add_field(name="Tipo:",   value="Fire", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ground/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def charmeleon(ctx): #005
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Charmeleon", value="Charmeleon mercilessly destroys its foes using its sharp claws. If it encounters a strong foe, it turns aggressive. In this excited state, the flame at the tip of its tail flares with a bluish white color.", inline=True)
    embed.add_field(name="Nº :", value="005", inline=True)
    embed.add_field(name="Altura:", value="1,1 m", inline=True)
    embed.add_field(name="Categoria:",  value="Flame", inline=True)
    embed.add_field(name="Tipo:",   value="Fire", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ground/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/005.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Charizard(ctx): #006
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Charizard", value="Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.", inline=True)
    embed.add_field(name="Nº :", value="006", inline=True)
    embed.add_field(name="Altura:", value="1,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Flame", inline=True)
    embed.add_field(name="Tipo:",   value="Fire/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Electric/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png')
    await bot.say (embed=embed)
 
@bot.command(pass_context=True)
async def charizard(ctx): #006
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Charizard", value="Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.", inline=True)
    embed.add_field(name="Nº :", value="006", inline=True)
    embed.add_field(name="Altura:", value="1,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Flame", inline=True)
    embed.add_field(name="Tipo:",   value="Fire/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Electric/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/006.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def MegaCharizardX(ctx): #006
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Mega Charizard X", value="Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.", inline=True)
    embed.add_field(name="Nº :", value="006", inline=True)
    embed.add_field(name="Altura:", value="1,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Flame", inline=True)
    embed.add_field(name="Tipo:",   value="Fire/Dragon", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ground/Rock/Dragon", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/006_f2.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def MegacharizardX(ctx): #006
    
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Mega Charizard X", value="Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.", inline=True)
    embed.add_field(name="Nº :", value="006", inline=True)
    embed.add_field(name="Altura:", value="1,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Flame", inline=True)
    embed.add_field(name="Tipo:",   value="Fire/Dragon", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ground/Rock/Dragon", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/006_f2.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def MegaCharizardY(ctx): #006
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Mega Charizard Y", value="Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.", inline=True)
    embed.add_field(name="Nº :", value="006", inline=True)
    embed.add_field(name="Altura:", value="1,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Flame", inline=True)
    embed.add_field(name="Tipo:",   value="Fire/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Eletric/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/006_f3.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def MegacharizardY(ctx): #006
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF80000) 
    embed.add_field(name="Nome: Mega Charizard Y", value="Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.", inline=True)
    embed.add_field(name="Nº :", value="006", inline=True)
    embed.add_field(name="Altura:", value="1,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Flame", inline=True)
    embed.add_field(name="Tipo:",   value="Fire/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Eletric/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Charmander ----> Charmeleon ----> Chalizard", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/006_f3.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Squirtle(ctx): #007
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x1D10DA) 
    embed.add_field(name="Nome: Squirtle", value="Squirtle's shell is not merely used for protection. The shell's rounded shape and the grooves on its surface help minimize resistance in water, enabling this Pokémon to swim at high speeds.", inline=True)
    embed.add_field(name="Nº :", value="007", inline=True)
    embed.add_field(name="Altura:", value="0,5 m", inline=True)
    embed.add_field(name="Categoria:",  value="Tiny Turtle", inline=True)
    embed.add_field(name="Tipo:",   value="Water", inline=True)
    embed.add_field(name="Fraquezas:",  value="Eletric/Grass", inline=True)
    embed.add_field(name="Evoluções:",  value="Squirtle ----> Wartortle ----> Blastoise", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def squirtle(ctx): #007
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x1D10DA) 
    embed.add_field(name="Nome: Squirtle", value="Squirtle's shell is not merely used for protection. The shell's rounded shape and the grooves on its surface help minimize resistance in water, enabling this Pokémon to swim at high speeds.", inline=True)
    embed.add_field(name="Nº :", value="007", inline=True)
    embed.add_field(name="Altura:", value="0,5 m", inline=True)
    embed.add_field(name="Categoria:",  value="Tiny Turtle", inline=True)
    embed.add_field(name="Tipo:",   value="Water", inline=True)
    embed.add_field(name="Fraquezas:",  value="Eletric/Grass", inline=True)
    embed.add_field(name="Evoluções:",  value="Squirtle ----> Wartortle ----> Blastoise", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Wartortle(ctx): #008
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x1D10DA) 
    embed.add_field(name="Nome: Wartortle", value="Its tail is large and covered with a rich, thick fur. The tail becomes increasingly deeper in color as Wartortle ages. The scratches on its shell are evidence of this Pokémon's toughness as a battler.", inline=True)
    embed.add_field(name="Nº :", value="008", inline=True)
    embed.add_field(name="Altura:", value="1,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Turtle", inline=True)
    embed.add_field(name="Tipo:",   value="Water", inline=True)
    embed.add_field(name="Fraquezas:",  value="Eletric/Grass", inline=True)
    embed.add_field(name="Evoluções:",  value="Squirtle ----> Wartortle ----> Blastoise", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def wartortle(ctx): #008
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x1D10DA) 
    embed.add_field(name="Nome: Wartortle", value="Its tail is large and covered with a rich, thick fur. The tail becomes increasingly deeper in color as Wartortle ages. The scratches on its shell are evidence of this Pokémon's toughness as a battler.", inline=True)
    embed.add_field(name="Nº :", value="008", inline=True)
    embed.add_field(name="Altura:", value="1,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Turtle", inline=True)
    embed.add_field(name="Tipo:",   value="Water", inline=True)
    embed.add_field(name="Fraquezas:",  value="Eletric/Grass", inline=True)
    embed.add_field(name="Evoluções:",  value="Squirtle ----> Wartortle ----> Blastoise", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/008.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Blastoise(ctx): #009
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x1D10DA) 
    embed.add_field(name="Nome: Blastoise ", value="Blastoise has water spouts that protrude from its shell. The water spouts are very accurate. They can shoot bullets of water with enough accuracy to strike empty cans from a distance of over 160 feet.", inline=True)
    embed.add_field(name="Nº :", value="009", inline=True)
    embed.add_field(name="Altura:", value="1,6 m", inline=True)
    embed.add_field(name="Categoria:",  value="Shellfish", inline=True)
    embed.add_field(name="Tipo:",   value="Water", inline=True)
    embed.add_field(name="Fraquezas:",  value="Eletric/Grass", inline=True)
    embed.add_field(name="Evoluções:",  value="Squirtle ----> Wartortle ----> Blastoise", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def blastoise(ctx): #009
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x1D10DA) 
    embed.add_field(name="Nome: Blastoise ", value="Blastoise has water spouts that protrude from its shell. The water spouts are very accurate. They can shoot bullets of water with enough accuracy to strike empty cans from a distance of over 160 feet.", inline=True)
    embed.add_field(name="Nº :", value="009", inline=True)
    embed.add_field(name="Altura:", value="1,6 m", inline=True)
    embed.add_field(name="Categoria:",  value="Shellfish", inline=True)
    embed.add_field(name="Tipo:",   value="Water", inline=True)
    embed.add_field(name="Fraquezas:",  value="Eletric/Grass", inline=True)
    embed.add_field(name="Evoluções:",  value="Squirtle ----> Wartortle ----> Blastoise", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/009.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Caterpie(ctx): #010
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x04B431) 
    embed.add_field(name="Nome: Caterpie ", value="Caterpie has a voracious appetite. It can devour leaves bigger than its body right before your eyes. From its antenna, this Pokémon releases a terrifically strong odor.", inline=True)
    embed.add_field(name="Nº :", value="010", inline=True)
    embed.add_field(name="Altura:", value="0,3 m", inline=True)
    embed.add_field(name="Categoria:",  value="Worm", inline=True)
    embed.add_field(name="Tipo:",   value="Bug", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Rock", inline=True)
    embed.add_field(name="Evoluções:",  value="Caterpie ----> Metapod ----> Butterfree", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def caterpie(ctx): #010
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x04B431) 
    embed.add_field(name="Nome: Caterpie ", value="Caterpie has a voracious appetite. It can devour leaves bigger than its body right before your eyes. From its antenna, this Pokémon releases a terrifically strong odor.", inline=True)
    embed.add_field(name="Nº :", value="010", inline=True)
    embed.add_field(name="Altura:", value="0,3 m", inline=True)
    embed.add_field(name="Categoria:",  value="Worm", inline=True)
    embed.add_field(name="Tipo:",   value="Bug", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Rock", inline=True)
    embed.add_field(name="Evoluções:",  value="Caterpie ----> Metapod ----> Butterfree", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/010.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Metapod(ctx): #011
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x04B431) 
    embed.add_field(name="Nome: Metapod  ", value="The shell covering this Pokémon's body is as hard as an iron slab. Metapod does not move very much. It stays still because it is preparing its soft innards for evolution inside the hard shell.", inline=True)
    embed.add_field(name="Nº :", value="011", inline=True)
    embed.add_field(name="Altura:", value="0,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Cocoon", inline=True)
    embed.add_field(name="Tipo:",   value="Bug", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Rock", inline=True)
    embed.add_field(name="Evoluções:",  value="Caterpie ----> Metapod ----> Butterfree", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def metapod(ctx): #011
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x04B431) 
    embed.add_field(name="Nome: Metapod  ", value="The shell covering this Pokémon's body is as hard as an iron slab. Metapod does not move very much. It stays still because it is preparing its soft innards for evolution inside the hard shell.", inline=True)
    embed.add_field(name="Nº :", value="011", inline=True)
    embed.add_field(name="Altura:", value="0,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Cocoon", inline=True)
    embed.add_field(name="Tipo:",   value="Bug", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Rock", inline=True)
    embed.add_field(name="Evoluções:",  value="Caterpie ----> Metapod ----> Butterfree", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/011.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Butterfree(ctx): #012
     
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x04B431) 
    embed.add_field(name="Nome: Butterfree  ", value="Butterfree has a superior ability to search for delicious honey from flowers. It can even search out, extract, and carry honey from flowers that are blooming over six miles from its nest.", inline=True)
    embed.add_field(name="Nº :", value="012", inline=True)
    embed.add_field(name="Altura:", value="1,1 m", inline=True)
    embed.add_field(name="Categoria:",  value="Butterfly", inline=True)
    embed.add_field(name="Tipo:",   value="Bug/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Rock/Ice/Electric", inline=True)
    embed.add_field(name="Evoluções:",  value="Caterpie ----> Metapod ----> Butterfree", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def butterfree(ctx): #12
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x04B431) 
    embed.add_field(name="Nome: Butterfree  ", value="Butterfree has a superior ability to search for delicious honey from flowers. It can even search out, extract, and carry honey from flowers that are blooming over six miles from its nest.", inline=True)
    embed.add_field(name="Nº :", value="012", inline=True)
    embed.add_field(name="Altura:", value="1,1 m", inline=True)
    embed.add_field(name="Categoria:",  value="Butterfly", inline=True)
    embed.add_field(name="Tipo:",   value="Bug/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fire/Flying/Rock/Ice/Electric", inline=True)
    embed.add_field(name="Evoluções:",  value="Caterpie ----> Metapod ----> Butterfree", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/012.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Latios(ctx): #381
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x0489B1) 
    embed.add_field(name="Nome: Latios  ", value="Latios has the ability to make others see an image of what it has seen or imagines in its head. This Pokémon is intelligent and understands human speech.", inline=True)
    embed.add_field(name="Nº :", value="381", inline=True)
    embed.add_field(name="Altura:", value="2,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Eon", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Bug/Dark/Dragon/Ghost/Ice/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/381.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def latios(ctx): #381
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x0489B1) 
    embed.add_field(name="Nome: Latios  ", value="Latios has the ability to make others see an image of what it has seen or imagines in its head. This Pokémon is intelligent and understands human speech.", inline=True)
    embed.add_field(name="Nº :", value="381", inline=True)
    embed.add_field(name="Altura:", value="2,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Eon", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Bug/Dark/Dragon/Ghost/Ice/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/381.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def MegaLatios(ctx): #381
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x0489B1) 
    embed.add_field(name="Nome: Mega Latios  ", value="Latios has the ability to make others see an image of what it has seen or imagines in its head. This Pokémon is intelligent and understands human speech.", inline=True)
    embed.add_field(name="Nº :", value="381", inline=True)
    embed.add_field(name="Altura:", value="2,3 m", inline=True)
    embed.add_field(name="Categoria:",  value="Eon", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Bug/Dark/Dragon/Ghost/Ice/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/381_f2.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Megalatios(ctx): #381
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x0489B1) 
    embed.add_field(name="Nome: Mega Latios  ", value="Latios has the ability to make others see an image of what it has seen or imagines in its head. This Pokémon is intelligent and understands human speech.", inline=True)
    embed.add_field(name="Nº :", value="381", inline=True)
    embed.add_field(name="Altura:", value="2,3 m", inline=True)
    embed.add_field(name="Categoria:",  value="Eon", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Bug/Dark/Dragon/Ghost/Ice/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/381_f2.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Palkia(ctx): #484
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFC0202) 
    embed.add_field(name="Nome: Palkia ", value="It is said to live in a gap in the spatial dimension parallel to ours. It appears in mythology.", inline=True)
    embed.add_field(name="Nº :", value="484", inline=True)
    embed.add_field(name="Altura:", value="4,2 m", inline=True)
    embed.add_field(name="Categoria:",  value="Spatial", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Water", inline=True)
    embed.add_field(name="Fraquezas:",  value="Dragon/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/484.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def palkia(ctx): #484
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFC0202) 
    embed.add_field(name="Nome: Palkia ", value="It is said to live in a gap in the spatial dimension parallel to ours. It appears in mythology.", inline=True)
    embed.add_field(name="Nº :", value="484", inline=True)
    embed.add_field(name="Altura:", value="4,2 m", inline=True)
    embed.add_field(name="Categoria:",  value="Spatial", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Water", inline=True)
    embed.add_field(name="Fraquezas:",  value="Dragon/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/484.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Rayquaza(ctx): #384

    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x03F5D8) 
    embed.add_field(name="Nome: Rayquaza ", value="Rayquaza is said to have lived for hundreds of millions of years. Legends remain of how it put to rest the clash between Kyogre and Groudon.", inline=True)
    embed.add_field(name="Nº :", value="384", inline=True)
    embed.add_field(name="Altura:", value="7,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Sky High", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Dragon/Fairy/Ice/Rock", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/384.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def rayquaza(ctx): #384

    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x03F5D8) 
    embed.add_field(name="Nome: Rayquaza ", value="Rayquaza is said to have lived for hundreds of millions of years. Legends remain of how it put to rest the clash between Kyogre and Groudon.", inline=True)
    embed.add_field(name="Nº :", value="384", inline=True)
    embed.add_field(name="Altura:", value="7,0 m", inline=True)
    embed.add_field(name="Categoria:",  value="Sky High", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Dragon/Fairy/Ice/Rock", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/384.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def MegaRayquaza(ctx): #384

    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x03F5D8) 
    embed.add_field(name="Nome: Mega Rayquaza ", value="Rayquaza is said to have lived for hundreds of millions of years. Legends remain of how it put to rest the clash between Kyogre and Groudon.", inline=True)
    embed.add_field(name="Nº :", value="384", inline=True)
    embed.add_field(name="Altura:", value="10,8 m", inline=True)
    embed.add_field(name="Categoria:",  value="Sky High", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Dragon/Fairy/Ice/Rock", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/384_f2.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Megarayquaza(ctx): #384

    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0x03F5D8) 
    embed.add_field(name="Nome: Mega Rayquaza ", value="Rayquaza is said to have lived for hundreds of millions of years. Legends remain of how it put to rest the clash between Kyogre and Groudon.", inline=True)
    embed.add_field(name="Nº :", value="384", inline=True)
    embed.add_field(name="Altura:", value="10,8 m", inline=True)
    embed.add_field(name="Categoria:",  value="Sky High", inline=True)
    embed.add_field(name="Tipo:",   value="Dragon/Flying", inline=True)
    embed.add_field(name="Fraquezas:",  value="Dragon/Fairy/Ice/Rock", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/384_f2.png')
    await bot.say (embed=embed)
         
@bot.command(pass_context=True)
async def Espurr(ctx): #677
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF908C4) 
    embed.add_field(name="Nome: Espurr  ", value="The organ that emits its intense psychic power is sheltered by its ears to keep power from leaking out.", inline=True)
    embed.add_field(name="Nº :", value="677", inline=True)
    embed.add_field(name="Altura:", value="0,3 m", inline=True)
    embed.add_field(name="Categoria:",  value="Restraint", inline=True)
    embed.add_field(name="Tipo:",   value="Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ghost/Dark/Bug", inline=True)
    embed.add_field(name="Evoluções:",  value="Espurr ----> Meowstic", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/677.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def espurr(ctx): #677
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF908C4) 
    embed.add_field(name="Nome: Espurr  ", value="The organ that emits its intense psychic power is sheltered by its ears to keep power from leaking out.", inline=True)
    embed.add_field(name="Nº :", value="677", inline=True)
    embed.add_field(name="Altura:", value="0,3 m", inline=True)
    embed.add_field(name="Categoria:",  value="Restraint", inline=True)
    embed.add_field(name="Tipo:",   value="Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ghost/Dark/Bug", inline=True)
    embed.add_field(name="Evoluções:",  value="Espurr ----> Meowstic", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/677.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Meowstic(ctx): #678
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF908C4) 
    embed.add_field(name="Nome: Meowstic", value="When in danger, it raises its ears and releases enough psychic power to grind a 10-ton truck into dust.", inline=True)
    embed.add_field(name="Nº :", value="678", inline=True)
    embed.add_field(name="Altura:", value="0,6 m", inline=True)
    embed.add_field(name="Categoria:",  value="Constraint", inline=True)
    embed.add_field(name="Tipo:",   value="Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ghost/Dark/Bug", inline=True)
    embed.add_field(name="Evoluções:",  value="Espurr ----> Meowstic", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/678.png')
    await bot.say (embed=embed)  
   
@bot.command(pass_context=True)
async def meowstic(ctx): #678
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xF908C4) 
    embed.add_field(name="Nome: Meowstic", value="When in danger, it raises its ears and releases enough psychic power to grind a 10-ton truck into dust.", inline=True)
    embed.add_field(name="Nº :", value="678", inline=True)
    embed.add_field(name="Altura:", value="0,6 m", inline=True)
    embed.add_field(name="Categoria:",  value="Constraint", inline=True)
    embed.add_field(name="Tipo:",   value="Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ghost/Dark/Bug", inline=True)
    embed.add_field(name="Evoluções:",  value="Espurr ----> Meowstic", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/678.png')
    await bot.say (embed=embed)  

@bot.command(pass_context=True)
async def Mew(ctx): #151
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFE2EF7) 
    embed.add_field(name="Nome: Mew", value="Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people.", inline=True)
    embed.add_field(name="Nº :", value="151", inline=True)
    embed.add_field(name="Altura:", value="0,4 m", inline=True)
    embed.add_field(name="Categoria:",  value="New Species", inline=True)
    embed.add_field(name="Tipo:",   value="Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ghost/Dark/Bug", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png')
    await bot.say (embed=embed)  

@bot.command(pass_context=True)
async def mew(ctx): #151
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFE2EF7) 
    embed.add_field(name="Nome: Mew", value="Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will, so it entirely avoids notice even if it approaches people.", inline=True)
    embed.add_field(name="Nº :", value="151", inline=True)
    embed.add_field(name="Altura:", value="0,4 m", inline=True)
    embed.add_field(name="Categoria:",  value="New Species", inline=True)
    embed.add_field(name="Tipo:",   value="Psychic", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ghost/Dark/Bug", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/151.png')
    await bot.say (embed=embed)  

@bot.command(pass_context=True)
async def Lucario(ctx): #448
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Lucario", value="By catching the aura emanating from others, it can read their thoughts and movements.", inline=True)
    embed.add_field(name="Nº :", value="448", inline=True)
    embed.add_field(name="Altura:", value="1,2 m", inline=True)
    embed.add_field(name="Categoria:",  value="Aura", inline=True)
    embed.add_field(name="Tipo:",   value="Fighting/Steel", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fighting/Fire/Ground", inline=True)
    embed.add_field(name="Evoluções:",  value="Riolu ----> Lucario", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/448.png')
    await bot.say (embed=embed)  
   
@bot.command(pass_context=True)
async def lucario(ctx): #448
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Lucario", value="By catching the aura emanating from others, it can read their thoughts and movements.", inline=True)
    embed.add_field(name="Nº :", value="448", inline=True)
    embed.add_field(name="Altura:", value="1,2 m", inline=True)
    embed.add_field(name="Categoria:",  value="Aura", inline=True)
    embed.add_field(name="Tipo:",   value="Fighting/Steel", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fighting/Fire/Ground", inline=True)
    embed.add_field(name="Evoluções:",  value="Riolu ----> Lucario", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/448.png')
    await bot.say (embed=embed) 

@bot.command(pass_context=True)
async def MegaLucario(ctx): #448
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Mega Lucario", value="By catching the aura emanating from others, it can read their thoughts and movements.", inline=True)
    embed.add_field(name="Nº :", value="448", inline=True)
    embed.add_field(name="Altura:", value="1,3 m", inline=True)
    embed.add_field(name="Categoria:",  value="Aura", inline=True)
    embed.add_field(name="Tipo:",   value="Fighting/Steel", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fighting/Fire/Ground", inline=True)
    embed.add_field(name="Evoluções:",  value="Riolu ----> Lucario", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/448_f2.png')
    await bot.say (embed=embed) 

@bot.command(pass_context=True)
async def Megalucario(ctx): #448
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Mega Lucario", value="By catching the aura emanating from others, it can read their thoughts and movements.", inline=True)
    embed.add_field(name="Nº :", value="448", inline=True)
    embed.add_field(name="Altura:", value="1,3 m", inline=True)
    embed.add_field(name="Categoria:",  value="Aura", inline=True)
    embed.add_field(name="Tipo:",   value="Fighting/Steel", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fighting/Fire/Ground", inline=True)
    embed.add_field(name="Evoluções:",  value="Riolu ----> Lucario", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/448_f2.png')
    await bot.say (embed=embed) 

@bot.command(pass_context=True)
async def Riolu(ctx): #447
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Riolu", value="It uses the shapes of auras, which change according to emotion, to communicate with others.", inline=True)
    embed.add_field(name="Nº :", value="447", inline=True)
    embed.add_field(name="Altura:", value="0,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Emanation", inline=True)
    embed.add_field(name="Tipo:",   value="Fighting", inline=True)
    embed.add_field(name="Fraquezas:",  value="Flying/Psychic/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Riolu ----> Lucario", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/447.png')
    await bot.say (embed=embed) 

@bot.command(pass_context=True)
async def riolu(ctx): #447
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Riolu", value="It uses the shapes of auras, which change according to emotion, to communicate with others.", inline=True)
    embed.add_field(name="Nº :", value="447", inline=True)
    embed.add_field(name="Altura:", value="0,7 m", inline=True)
    embed.add_field(name="Categoria:",  value="Emanation", inline=True)
    embed.add_field(name="Tipo:",   value="Fighting", inline=True)
    embed.add_field(name="Fraquezas:",  value="Flying/Psychic/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Riolu ----> Lucario", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/447.png')
    await bot.say (embed=embed) 

@bot.command(pass_context=True)
async def Arceus(ctx): #493
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Arceus", value="According to the legends of Sinnoh, this Pokémon emerged from an egg and shaped all there is in this world.", inline=True)
    embed.add_field(name="Nº :", value="493", inline=True)
    embed.add_field(name="Altura:", value="3,2 m", inline=True)
    embed.add_field(name="Categoria:",  value="Alpha", inline=True)
    embed.add_field(name="Tipo:",   value="Normal", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fighting", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/493.png')
    await bot.say (embed=embed) 

@bot.command(pass_context=True)
async def arceus(ctx): #493
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Arceus", value="According to the legends of Sinnoh, this Pokémon emerged from an egg and shaped all there is in this world.", inline=True)
    embed.add_field(name="Nº :", value="493", inline=True)
    embed.add_field(name="Altura:", value="3,2 m", inline=True)
    embed.add_field(name="Categoria:",  value="Alpha", inline=True)
    embed.add_field(name="Tipo:",   value="Normal", inline=True)
    embed.add_field(name="Fraquezas:",  value="Fighting", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/493.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Giratina(ctx): #487
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Giratina", value="This Pokémon is said to live in a world on the reverse side of ours, where common knowledge is distorted and strange.", inline=True)
    embed.add_field(name="Nº :", value="487", inline=True)
    embed.add_field(name="Altura:", value="4,5 m", inline=True)
    embed.add_field(name="Categoria:",  value="Renegade", inline=True)
    embed.add_field(name="Tipo:",   value="Ghost/Dragon", inline=True)
    embed.add_field(name="Fraquezas:",  value="Dark/Dragon/Ghost/Ice/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/487.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def giratina(ctx): #487
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Giratina", value="This Pokémon is said to live in a world on the reverse side of ours, where common knowledge is distorted and strange.", inline=True)
    embed.add_field(name="Nº :", value="487", inline=True)
    embed.add_field(name="Altura:", value="4,5 m", inline=True)
    embed.add_field(name="Categoria:",  value="Renegade", inline=True)
    embed.add_field(name="Tipo:",   value="Ghost/Dragon", inline=True)
    embed.add_field(name="Fraquezas:",  value="Dark/Dragon/Ghost/Ice/Fairy", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/487.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def Entei(ctx): #244
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Entei", value="Entei embodies the passion of magma. This Pokémon is thought to have been born in the eruption of a volcano. It sends up massive bursts of fire that utterly consume all that they touch.", inline=True)
    embed.add_field(name="Nº :", value="244", inline=True)
    embed.add_field(name="Altura:", value="2,1 m", inline=True)
    embed.add_field(name="Categoria:",  value="Volcano", inline=True)
    embed.add_field(name="Tipo:",   value="Fire", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ground/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/244.png')
    await bot.say (embed=embed)

@bot.command(pass_context=True)
async def entei(ctx): #244
    embed = discord.Embed(title="{}".format("Pokémon"),descripition ="", color = 0xFACC2E) 
    embed.add_field(name="Nome: Entei", value="Entei embodies the passion of magma. This Pokémon is thought to have been born in the eruption of a volcano. It sends up massive bursts of fire that utterly consume all that they touch.", inline=True)
    embed.add_field(name="Nº :", value="244", inline=True)
    embed.add_field(name="Altura:", value="2,1 m", inline=True)
    embed.add_field(name="Categoria:",  value="Volcano", inline=True)
    embed.add_field(name="Tipo:",   value="Fire", inline=True)
    embed.add_field(name="Fraquezas:",  value="Ground/Rock/Water", inline=True)
    embed.add_field(name="Evoluções:",  value="Este Pokémon não evolui.", inline=True)
    embed.set_thumbnail(url='https://assets.pokemon.com/assets/cms2/img/pokedex/full/244.png')
    await bot.say (embed=embed)


bot.run("")

